language: node_js
sudo: false
node_js:
  - '10'

cache:
  yarn: true
  timeout: 1000
  directories:
    - $HOME/.npm
    - 'node_modules'

before_install:
  - nvm install 10

install:
  - npm install

script:
  - npm run build

deploy:
  provider: script
  script: 'npm run deploy'
  skip_cleanup: true
  on:
    branch: master
