language: node_js
sudo: false
node_js:
  - '10'

cache:
  yarn: true
  timeout: 1000
  directories:
    - $HOME/.npm
    - 'node_modules'

before_install:
  - nvm install 10
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn install

script:
  - yarn run build

deploy:
  provider: script
  script: 'yarn run deploy'
  skip_cleanup: true
  on:
    branch: master
